/** Thanas & upazilas per district — deduplicated, incl. DMP/CMP city thanas. */
import type { BdDistrict } from '@/lib/checkout/bd-districts'

export const BD_THANAS_BY_DISTRICT: Record<BdDistrict, readonly string[]> = {
  "Bagerhat": [
    "Bagerhat Sadar",
    "Chitalmari",
    "Fakirhat",
    "Kachua",
    "Mollahat",
    "Mongla",
    "Morrelganj",
    "Rampal",
    "Sarankhola"
  ],
  "Bandarban": [
    "Ali kadam",
    "Bandarban Sadar",
    "Lama",
    "Naikhongchhari",
    "Rowangchhari",
    "Ruma",
    "Thanchi"
  ],
  "Barguna": [
    "Amtali",
    "Bamna",
    "Barguna Sadar",
    "Betagi",
    "Patharghata",
    "Taltali"
  ],
  "Barishal": [
    "Agailjhara",
    "Babuganj",
    "Bakerganj",
    "Banaripara",
    "Barisal Sadar",
    "Gaurnadi",
    "Hizla",
    "Mehendiganj",
    "Muladi",
    "Wazirpur"
  ],
  "Bhola": [
    "Bhola Sadar",
    "Burhanuddin",
    "Char Fasson",
    "Daulatkhan",
    "Lalmohan",
    "Manpura",
    "Tazumuddin"
  ],
  "Bogura": [
    "Adamdighi",
    "Bogra Sadar",
    "Dhunat",
    "Dhupchanchia",
    "Gabtali",
    "Kahaloo",
    "Nandigram",
    "Sahajanpur",
    "Sariakandi",
    "Sherpur",
    "Shibganj",
    "Sonatala"
  ],
  "Brahmanbaria": [
    "Akhaura",
    "Ashuganj",
    "Bancharampur",
    "Bijoynagar",
    "Brahmanbaria Sadar",
    "Kasba",
    "Nabinagar",
    "Nasirnagar",
    "Sarail",
    "Shahbazpur Town"
  ],
  "Chandpur": [
    "Chandpur Sadar",
    "Faridganj",
    "Haimchar",
    "Haziganj",
    "Kachua",
    "Matlab Dakkhin",
    "Matlab Uttar",
    "Shahrasti"
  ],
  "Chapai Nawabganj": [
    "Bholahat",
    "Chapainawabganj Sadar",
    "Gomastapur",
    "Nachole",
    "Shibganj"
  ],
  "Chattogram": [
    "Akbar Shah",
    "Anwara",
    "Bakalia",
    "Bandar",
    "Banshkhali",
    "Bayezid Bostami",
    "Boalkhali",
    "Chandanaish",
    "Chandgaon",
    "Chawk Bazar",
    "Chittagong Kotwali",
    "Double Mooring",
    "EPZ",
    "Fatikchhari",
    "Halishahar",
    "Hathazari",
    "Karnafuli",
    "Khulshi",
    "Kotwali",
    "Lohagara",
    "Mirsharai",
    "Pahartali",
    "Panchlaish",
    "Patenga",
    "Patiya",
    "Rangunia",
    "Raozan",
    "Sadarghat",
    "Sandwip",
    "Satkania",
    "Sitakunda"
  ],
  "Chuadanga": [
    "Alamdanga",
    "Chuadanga Sadar",
    "Damurhuda",
    "Jibannagar"
  ],
  "Cox's Bazar": [
    "Chakaria",
    "Cox's Bazar Sadar",
    "Eidgaon",
    "Kutubdia",
    "Maheshkhali",
    "Pekua",
    "Ramu",
    "Teknaf",
    "Ukhia"
  ],
  "Cumilla": [
    "Barura",
    "Brahmanpara",
    "Burichong",
    "Chandina",
    "Chauddagram",
    "Comilla Sadar",
    "Comilla Sadar South",
    "Daudkandi",
    "Debidwar",
    "Homna",
    "Laksam",
    "Meghna",
    "Monohorgonj",
    "Muradnagar",
    "Nangalkot",
    "Titas"
  ],
  "Dhaka": [
    "Adabor",
    "Ashulia",
    "Badda",
    "Banani",
    "Bangshal",
    "Bhasan Tek",
    "Bhatara",
    "Biman Bandar",
    "Cantonment",
    "Chak Bazar",
    "Dakshinkhan",
    "Darus Salam",
    "Demra",
    "Dhamrai",
    "Dhanmondi",
    "Dohar",
    "Gendaria",
    "Gulshan",
    "Hatirjheel",
    "Hazaribagh",
    "Jatrabari",
    "Kadamtali",
    "Kafrul",
    "Kalabagan",
    "Kamrangir Char",
    "Keraniganj",
    "Keraniganj (South)",
    "Khilgaon",
    "Khilkhet",
    "Kotwali",
    "Lalbagh",
    "Mirpur",
    "Mohammadpur",
    "Motijheel",
    "Mugda Para",
    "Nawabganj",
    "New Market",
    "Pallabi",
    "Paltan",
    "Ramna",
    "Rampura",
    "Rupnagar",
    "Sabujbagh",
    "Savar",
    "Shah Ali",
    "Shahbagh",
    "Shahjahanpur",
    "Sher-E-Bangla Nagar",
    "Shyampur",
    "Sutrapur",
    "Tejgaon",
    "Tejgaon Ind. Area",
    "Turag",
    "Uttar Khan",
    "Uttara",
    "Uttara Paschim",
    "Uttara Purba",
    "Vatara",
    "Wari"
  ],
  "Dinajpur": [
    "Biral",
    "Birampur",
    "Birganj",
    "Bochaganj",
    "Chirirbandar",
    "Dinajpur Sadar",
    "Ghoraghat",
    "Hakimpur",
    "Kaharole",
    "Khansama",
    "Nawabganj",
    "Parbatipur",
    "Phulbari"
  ],
  "Faridpur": [
    "Alfadanga",
    "Bhanga",
    "Boalmari",
    "Charbhadrasan",
    "Faridpur Sadar",
    "Madhukhali",
    "Nagarkanda",
    "Sadarpur",
    "Shaltha"
  ],
  "Feni": [
    "Chagalnaiya",
    "Daganbhyan",
    "Feni Sadar",
    "Fhulgazi",
    "Parshuram",
    "Sonagazi"
  ],
  "Gaibandha": [
    "Fulchhari",
    "Gaibandha Sadar",
    "Gobindaganj",
    "Palashbari",
    "Sadullapur",
    "Saghata",
    "Sundarganj"
  ],
  "Gazipur": [
    "Bason",
    "Gacha",
    "Gazipur (Sadar)",
    "Gazipur Sadar-Joydebpur",
    "Kaliakior",
    "Kaliganj",
    "Kapasia",
    "Kashimpur",
    "Konabari",
    "Pubail",
    "Sripur",
    "Tongi",
    "Tongi (North)",
    "Tongi (West)"
  ],
  "Gopalganj": [
    "Gopalganj Sadar",
    "Kashiani",
    "Kotalipara",
    "Muksudpur",
    "Tungipara"
  ],
  "Habiganj": [
    "Ajmiriganj",
    "Bahubal",
    "Baniachang",
    "Chunarughat",
    "Habiganj Sadar",
    "Lakhai",
    "Madhabpur",
    "Nabiganj",
    "Shaistagonj"
  ],
  "Jamalpur": [
    "Baksiganj",
    "Dewanganj",
    "Islampur",
    "Jamalpur Sadar",
    "Madarganj",
    "Melandaha",
    "Narundi Police I.C",
    "Sarishabari"
  ],
  "Jashore": [
    "Abhaynagar",
    "Bagherpara",
    "Chaugachha",
    "Jessore Sadar",
    "Jhikargachha",
    "Keshabpur",
    "Manirampur",
    "Sharsha"
  ],
  "Jhalokathi": [
    "Jhalokati Sadar",
    "Kathalia",
    "Nalchity",
    "Rajapur"
  ],
  "Jhenaidah": [
    "Harinakunda",
    "Jhenaidah Sadar",
    "Kaliganj",
    "Kotchandpur",
    "Maheshpur",
    "Shailkupa"
  ],
  "Joypurhat": [
    "Akkelpur",
    "Joypurhat Sadar",
    "Kalai",
    "Khetlal",
    "Panchbibi"
  ],
  "Khagrachhari": [
    "Dighinala",
    "Khagrachhari",
    "Lakshmichhari",
    "Mahalchhari",
    "Manikchhari",
    "Matiranga",
    "Panchhari",
    "Ramgarh"
  ],
  "Khulna": [
    "Batiaghata",
    "Dacope",
    "Daulatpur",
    "Dighalia",
    "Dumuria",
    "Khalishpur",
    "Khan Jahan Ali",
    "Khulna Sadar",
    "Koyra",
    "Paikgachha",
    "Phultala",
    "Rupsa",
    "Sonadanga",
    "Terokhada"
  ],
  "Kishoreganj": [
    "Astagram",
    "Bajitpur",
    "Bhairab",
    "Hossainpur",
    "Itna",
    "Karimganj",
    "Katiadi",
    "Kishoreganj Sadar",
    "Kuliarchar",
    "Mithamain",
    "Nikli",
    "Pakundia",
    "Tarail"
  ],
  "Kurigram": [
    "Bhurungamari",
    "Char Rajibpur",
    "Chilmari",
    "Kurigram Sadar",
    "Nageshwari",
    "Phulbari",
    "Rajarhat",
    "Rowmari",
    "Ulipur"
  ],
  "Kushtia": [
    "Bheramara",
    "Daulatpur",
    "Khoksa",
    "Kumarkhali",
    "Kushtia Sadar",
    "Mirpur"
  ],
  "Lakshmipur": [
    "Komol Nagar",
    "Lakshmipur Sadar",
    "Raipur",
    "Ramganj",
    "Ramgati"
  ],
  "Lalmonirhat": [
    "Aditmari",
    "Hatibandha",
    "Kaliganj",
    "Lalmonirhat Sadar",
    "Patgram"
  ],
  "Madaripur": [
    "Dasar",
    "Kalkini",
    "Madaripur Sadar",
    "Rajoir",
    "Shibchar"
  ],
  "Magura": [
    "Magura Sadar",
    "Mohammadpur",
    "Shalikha",
    "Sreepur"
  ],
  "Manikganj": [
    "Daulatpur",
    "Ghior",
    "Harirampur",
    "Manikganj Sadar",
    "Saturia",
    "Shibalaya",
    "Singair"
  ],
  "Meherpur": [
    "Gangni",
    "Meherpur Sadar",
    "Mujibnagar"
  ],
  "Moulvibazar": [
    "Barlekha",
    "Juri",
    "Kamalganj",
    "Kulaura",
    "Moulvibazar Sadar",
    "Rajnagar",
    "Sreemangal"
  ],
  "Munshiganj": [
    "Gazaria",
    "Lohajang",
    "Munshiganj Sadar",
    "Sirajdikhan",
    "Sreenagar",
    "Tongibari"
  ],
  "Mymensingh": [
    "Bhaluka",
    "Dhobaura",
    "Fulbaria",
    "Gaffargaon",
    "Gauripur",
    "Haluaghat",
    "Ishwarganj",
    "Muktagachha",
    "Mymensingh Sadar",
    "Nandail",
    "Phulpur",
    "Tarakanda",
    "Trishal"
  ],
  "Naogaon": [
    "Atrai",
    "Badalgachhi",
    "Dhamoirhat",
    "Manda",
    "Mohadevpur",
    "Naogaon Sadar",
    "Niamatpur",
    "Patnitala",
    "Porsha",
    "Raninagar",
    "Sapahar"
  ],
  "Narail": [
    "Kalia",
    "Lohagara",
    "Narail Sadar"
  ],
  "Narayanganj": [
    "Araihazar",
    "Bandar",
    "Fatullah",
    "Fotullah",
    "Naryanganj Sadar",
    "Rupganj",
    "Siddirgonj",
    "Sonargaon"
  ],
  "Narsingdi": [
    "Belabo",
    "Monohardi",
    "Narsingdi Sadar",
    "Palash",
    "Raipura",
    "Shibpur"
  ],
  "Natore": [
    "Bagatipara",
    "Baraigram",
    "Gurudaspur",
    "Lalpur",
    "Natore Sadar",
    "Singra"
  ],
  "Netrokona": [
    "Atpara",
    "Barhatta",
    "Durgapur",
    "Kalmakanda",
    "Kendua",
    "Khaliajuri",
    "Madan",
    "Mohanganj",
    "Netrokona Sadar",
    "Purbadhala"
  ],
  "Nilphamari": [
    "Dimla",
    "Domar",
    "Jaldhaka",
    "Kishoreganj",
    "Nilphamari Sadar",
    "Saidpur"
  ],
  "Noakhali": [
    "Begumganj",
    "Chatkhil",
    "Companyganj",
    "Hatia",
    "Kobirhat",
    "Noakhali Sadar",
    "Shenbag",
    "Sonaimuri",
    "Suborno Char"
  ],
  "Pabna": [
    "Atgharia",
    "Bera",
    "Bhangura",
    "Chatmohar",
    "Faridpur",
    "Ishwardi",
    "Pabna Sadar",
    "Santhia",
    "Sujanagar"
  ],
  "Panchagarh": [
    "Atwari",
    "Boda",
    "Debiganj",
    "Panchagarh Sadar",
    "Tetulia"
  ],
  "Patuakhali": [
    "Bauphal",
    "Dashmina",
    "Dumki",
    "Galachipa",
    "Kalapara",
    "Mirzaganj",
    "Patuakhali Sadar",
    "Rangabali"
  ],
  "Pirojpur": [
    "Bhandaria",
    "Kaukhali",
    "Mathbaria",
    "Nazirpur",
    "Nesarabad",
    "Pirojpur Sadar",
    "Zianagar"
  ],
  "Rajbari": [
    "Baliakandi",
    "Goalandaghat",
    "Kalukhali",
    "Pangsha",
    "Rajbari Sadar"
  ],
  "Rajshahi": [
    "Bagha",
    "Bagmara",
    "Boalia",
    "Charghat",
    "Durgapur",
    "Godagari",
    "Mohanpur",
    "Motihar",
    "Paba",
    "Puthia",
    "Rajpara",
    "Shaheb Bazar",
    "Tanore"
  ],
  "Rangamati": [
    "Bagaichhari",
    "Barkal",
    "Belaichhari",
    "Juraichhari",
    "Kaptai",
    "Kaukhali",
    "Langadu",
    "Nannerchar",
    "Rajasthali",
    "Rangamati Sadar"
  ],
  "Rangpur": [
    "Badarganj",
    "Gangachara",
    "Kaunia",
    "Mithapukur",
    "Pirgachha",
    "Pirganj",
    "Rangpur Sadar",
    "Taraganj"
  ],
  "Satkhira": [
    "Assasuni",
    "Debhata",
    "Kalaroa",
    "Kaliganj",
    "Satkhira Sadar",
    "Shyamnagar",
    "Tala"
  ],
  "Shariatpur": [
    "Bhedarganj",
    "Damudya",
    "Gosairhat",
    "Jajira",
    "Naria",
    "Shariatpur Sadar"
  ],
  "Sherpur": [
    "Jhenaigati",
    "Nakla",
    "Nalitabari",
    "Sherpur Sadar",
    "Sreebardi"
  ],
  "Sirajganj": [
    "Belkuchi",
    "Chauhali",
    "Kamarkhanda",
    "Kazipur",
    "Raiganj",
    "Shahjadpur",
    "Sirajganj Sadar",
    "Tarash",
    "Ullahpara"
  ],
  "Sunamganj": [
    "Bishwamvarpur",
    "Chhatak",
    "Derai",
    "Dharampasha",
    "Dowarabazar",
    "Jagannathpur",
    "Jamalganj",
    "Madhyanagar",
    "Shanthiganj",
    "Sulla",
    "Sunamganj Sadar",
    "Tahirpur"
  ],
  "Sylhet": [
    "Balaganj",
    "Beanibazar",
    "Bishwanath",
    "Companiganj",
    "Dakshin Surma",
    "Fenchuganj",
    "Golapganj",
    "Gowainghat",
    "Jaintiapur",
    "Kanaighat",
    "Osmaninagar",
    "Sylhet Sadar",
    "Zakiganj"
  ],
  "Tangail": [
    "Basail",
    "Bhuapur",
    "Delduar",
    "Dhanbari",
    "Ghatail",
    "Gopalpur",
    "Kalihati",
    "Madhupur",
    "Mirzapur",
    "Nagarpur",
    "Sakhipur",
    "Tangail Sadar"
  ],
  "Thakurgaon": [
    "Baliadangi",
    "Haripur",
    "Pirganj",
    "Ranisankail",
    "Thakurgaon Sadar"
  ]
} as const

export function getThanasForDistrict(district: string): readonly string[] {
  return (BD_THANAS_BY_DISTRICT as Record<string, readonly string[]>)[district] ?? []
}

export function isBdThana(district: string, thana: string): boolean {
  return getThanasForDistrict(district).includes(thana)
}
