import type { InvoiceInput } from './types.js'

export const sampleInvoice: InvoiceInput = {
  invoiceNumber: 'INV-SPL-2026-0042',
  orderId: 'ord_sample_001',
  issueDate: new Date().toLocaleDateString('en-BD', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  }),
  customerName: 'Ayesha Rahman',
  customerPhone: '01712345678',
  customerEmail: 'ayesha@example.com',
  shippingAddress: 'House 12, Road 5, Block C',
  shippingCity: 'Uttara',
  shippingDistrict: 'Dhaka',
  paymentMethod: 'Cash on Delivery',
  paymentStatus: 'Pending',
  orderStatus: 'Confirmed',
  subtotal: 12500,
  deliveryCharge: 120,
  discount: 500,
  total: 12120,
  couponCode: 'SPLARO10',
  courierName: 'Steadfast',
  trackingCode: 'SF-88442211',
  items: [
    {
      productName: 'Premium Embroidered Abaya',
      sku: 'ABY-GLD-01',
      size: 'M',
      color: 'Black',
      quantity: 1,
      unitPrice: 8500,
      discount: 0,
      lineTotal: 8500,
    },
    {
      productName: 'Silk Hijab — Champagne',
      sku: 'HJB-CHP-02',
      size: 'Free',
      color: 'Champagne',
      quantity: 2,
      unitPrice: 2000,
      discount: 0,
      lineTotal: 4000,
    },
  ],
}
