import { flatAdminRoutes } from '@/lib/navigation/admin-nav'

/**
 * Module routes that shipped a dedicated panel before the DC unification.
 *
 * Consumed by `module-maturity.ts` as the LIVE allow-list. Soft-locked URL
 * shells must not appear here — only DC_BESPOKE + dedicated pages.
 */
export const REGISTERED_MODULE_HREFS: string[] = [
  '/dashboard/orders',
  '/dashboard/products',
  '/dashboard/customers',
  '/dashboard/wholesale-leads',
  '/dashboard/wholesale-stock',
  '/dashboard/packing-station',
  '/dashboard/courier-hub',
  '/dashboard/finance/partner-accounts',
  '/dashboard/finance/daily-closing',
  '/dashboard/settings',
  '/dashboard/mobile-screens',
  '/dashboard/executive/export-center',
  '/dashboard/executive/notification-center',
  '/dashboard/legal-pages',
  '/dashboard/hero-slider',
  '/dashboard/menu-control',
  '/dashboard/product-reviews',
  '/dashboard/collections',
  '/dashboard/categories',
  '/dashboard/inventory',
  '/dashboard/admin-users',
  '/dashboard/security-center',
  '/dashboard/ai-agent',
  '/dashboard/seo-health',
  '/dashboard/automation-rules',
  '/dashboard/all-integrations',
  '/dashboard/media-library',
  '/dashboard/home-page',
  '/dashboard/api-health',
  '/dashboard/wms/overview',
  '/dashboard/procurement/overview',
  '/dashboard/procurement/purchase-orders',
  '/dashboard/procurement/suppliers',
  '/dashboard/procurement/goods-received',
  '/dashboard/returns-rma',
  '/dashboard/operations',
  '/dashboard/finance/finance-reports',
  '/dashboard/finance/order-profit',
  '/dashboard/finance/expenses',
  '/dashboard/finance/profit-loss',
  '/dashboard/coupons',
  '/dashboard/campaigns',
  '/dashboard/sms',
  '/dashboard/automation/google-sheets-sync',
  '/dashboard/bulk',
  '/dashboard/analytics',
  '/dashboard/telegram-bot',
  '/dashboard/footwear-page',
  '/dashboard/theme-builder',
  '/dashboard/lookbooks',
  '/dashboard/reels',
  '/dashboard/blog',
  '/dashboard/cms',
  '/dashboard/landing-pages',
  // Thin hubs (all-nav-live)
  '/dashboard/pos',
  '/dashboard/invoices',
  '/dashboard/transactions',
  '/dashboard/subscriptions',
  '/dashboard/brands',
  '/dashboard/webhooks',
  '/dashboard/support/helpdesk',
  '/dashboard/delivery/agents',
  '/dashboard/company/dashboard',
  '/dashboard/production/overview',
  '/dashboard/google-workspace/connect',
  '/dashboard/google-workspace/gmail',
  '/dashboard/google-workspace/drive',
  '/dashboard/google-workspace/oauth-settings',
  '/dashboard/google-workspace/sync-logs',
  '/dashboard/logs',
  '/dashboard/developer/api-center',
  '/dashboard/observability/center',
]

export function getAllModuleHrefs(): string[] {
  return flatAdminRoutes.map((route) => route.href)
}
