location @r2_uploads {
    proxy_pass https://pub-4284fd31b94949469822ca642b829b59.r2.dev;
    proxy_set_header Host pub-4284fd31b94949469822ca642b829b59.r2.dev;
    proxy_ssl_server_name on;
    proxy_ssl_name pub-4284fd31b94949469822ca642b829b59.r2.dev;
    add_header Cache-Control "public, max-age=31536000, immutable";
    add_header X-Content-Type-Options nosniff always;
    add_header Access-Control-Allow-Origin "https://admin.splaro.co" always;
    access_log off;
}
