const APP_ROOT = process.env.SPLARO_APP_DIR || '/var/www/splaro';

module.exports = {
  apps: [
    {
      name: 'splaro-web',
      cwd: `${APP_ROOT}/apps/web`,
      script: 'node',
      args: '.next/standalone/apps/web/server.js',
      env: {
        NODE_ENV: 'production',
        PORT: 3000,
        HOSTNAME: '127.0.0.1',
        NEXT_PUBLIC_SITE_URL: process.env.NEXT_PUBLIC_SITE_URL || 'https://splaro.co',
        NEXT_PUBLIC_ADMIN_URL: process.env.NEXT_PUBLIC_ADMIN_URL || 'https://admin.splaro.co',
        NEXT_PUBLIC_API_URL: process.env.NEXT_PUBLIC_API_URL || 'https://api.splaro.co/api/v1',
      },
      instances: 2,
      exec_mode: 'cluster',
      watch: false,
      max_memory_restart: '512M',
      log_file: '/var/log/splaro/web.log',
      error_file: '/var/log/splaro/web-error.log',
      out_file: '/var/log/splaro/web-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      restart_delay: 4000,
      autorestart: true,
    },
    {
      name: 'splaro-admin',
      cwd: `${APP_ROOT}/apps/admin`,
      script: 'node',
      args: '.next/standalone/apps/admin/server.js',
      env: {
        NODE_ENV: 'production',
        PORT: 3001,
        HOSTNAME: '127.0.0.1',
        NEXT_PUBLIC_SITE_URL: process.env.NEXT_PUBLIC_SITE_URL || 'https://splaro.co',
        NEXT_PUBLIC_ADMIN_URL: process.env.NEXT_PUBLIC_ADMIN_URL || 'https://admin.splaro.co',
        NEXT_PUBLIC_API_URL: process.env.NEXT_PUBLIC_API_URL || 'https://api.splaro.co/api/v1',
      },
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      max_memory_restart: '512M',
      log_file: '/var/log/splaro/admin.log',
      error_file: '/var/log/splaro/admin-error.log',
      out_file: '/var/log/splaro/admin-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      autorestart: true,
    },
    {
      name: 'splaro-api',
      cwd: `${APP_ROOT}/apps/api`,
      script: 'dist/main.js',
      env: {
        NODE_ENV: 'production',
        API_PORT: 4000,
        WEB_URL: process.env.WEB_URL || 'https://splaro.co',
        ADMIN_URL: process.env.ADMIN_URL || 'https://admin.splaro.co',
        API_URL: process.env.API_URL || 'https://api.splaro.co',
        CORS_ORIGINS: process.env.CORS_ORIGINS || 'https://splaro.co,https://admin.splaro.co',
      },
      instances: 2,
      exec_mode: 'cluster',
      watch: false,
      max_memory_restart: '768M',
      log_file: '/var/log/splaro/api.log',
      error_file: '/var/log/splaro/api-error.log',
      out_file: '/var/log/splaro/api-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      restart_delay: 4000,
      autorestart: true,
      kill_timeout: 10000,
    },
    {
      name: 'splaro-worker',
      cwd: `${APP_ROOT}/apps/worker`,
      script: 'dist/index.js',
      env: {
        NODE_ENV: 'production',
        REDIS_HOST: '127.0.0.1',
        REDIS_PORT: 6379,
      },
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      max_memory_restart: '512M',
      log_file: '/var/log/splaro/worker.log',
      error_file: '/var/log/splaro/worker-error.log',
      out_file: '/var/log/splaro/worker-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      autorestart: true,
      restart_delay: 5000,
    },
    {
      name: 'splaro-print',
      cwd: `${APP_ROOT}/tools/print-service`,
      script: 'dist/index.js',
      env: {
        NODE_ENV: 'production',
        PORT: 5000,
      },
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      max_memory_restart: '256M',
      log_file: '/var/log/splaro/print.log',
      autorestart: true,
    },
  ],
}
