# ── REDIRECT HTTP → HTTPS (admin) ────────────────────────────
server {
    listen 80;
    listen [::]:80;
    server_name admin.splaro.com.bd;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

# ── REDIRECT HTTP → HTTPS (api) ──────────────────────────────
server {
    listen 80;
    listen [::]:80;
    server_name api.splaro.com.bd;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}
