export * from './hero-default-slides'
export * from './local-placeholders'
export * from './brand-icons'
export * from './delivery-zones'
export * from './domains'
export * from './feature-flags'
// invoice-access uses Node crypto — import from '@splaro/config/invoice-access' only
// (never from this barrel) so client bundles do not pull ~325KB asn1/bn.js polyfills.
export * from './invoice-brand'
export * from './splaro-invoice-brand'
export * from './strip-extension-attrs'
export * from './order-code'
export * from './customer-code'
export * from './payment-code'
export * from './category-tree-defaults'
